### ISSUE TITLE
Major User Interactions Checklist

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#100]
# Demo Checklist
This is a reference for all the frontend mock features we're looking to add and check for the demo.

### Auth Page
- [x] 1. Auth: The user is able to "Sign In" and continue to the home page. (#86)
    - [x] a. Mobile Resolution looks good.
- [x] 2. Auth: The user is able to "Register" and continue to the home page. (#86) 
    - [x] a. Mobile Resolution looks good.

### Other Pages
- [x] 3. Error: The user is able to go back to the home page after reaching a 404 page. (#90) 
    - [x] a. Mobile Resolution looks good.

### Home Page (Search Results page)
- [x] 4. Home: The user is able to sort current home page by votes or by date.
- [x] 5. Home: The user is able to open the comments to one search result item and see them sorted by votes. (#80)
- [x] 6. Home: The user is able to click the user's names to go to the user profile page. (#83)
- [x] 7. Home: Mobile Resolution of the home page looks good, including when the user opens the nested comments. (#87 #88)
- [x] 8. Home: The user is able to click on any expertise to see the sorted results.
- [x] 9. Home: The user is able to click the top navigation to view filtered results by Ob, Qu, Hy.

### Detail Node Page
- [x] 8. Detail Node: The user is able to click on the author's name to go to the user profile page. (#83)
- [x] 9. Detail Node: The user is able to click on the upvote or the downvote icon to update number of votes +1 or -1 (mock) (#89)
- [x] 10. Detail Node: The user is able to click on the number for "Cites: { citedNode }" to see them on the **left** side panel. There should only be one item there. (#77)
- [x] 11. Detail Node: The user is able to click on the numbers for "Cited By: 1 Observation / 1 Question / 1 Hypothesis" to see them on the **right** side panel. There may be multiple items here. (#78)
- [x] 12. Detail Node: The user is able to click on "Review: {number}" to see in the right side panel a section for "Top Reviews" and a list of reviews. (#81)
- [x] 13. Detail Node: From some node with `id: "B"`, The user is able to click on "Linked From: {origination}" to navigate to the parent node `id: "A"`. (Ideally, this parent node should have in "Cited By: {numbers}" where the user can navigate back to the node with `id: "B"` from the right panel from item number 11 above.)
- [x] 14. Detail Node: The user can highlight some text to show the pointing menu to create a new post. 
    - [x] a. The user should be able to see the text that they highlighted in the right side panel in the section that says "You highlighted: { highlightedText }". (#92)
    - [x] b. "Post Type" should match what the user clicked.
    - [x] c. "In Response To" section should match the current post.
    - [x] d. When the user clicks "Post" it should close the menu.
- [x] 15. Detail Node: The left side panel content (Cites) should look good on mobile. (#91)
- [x] 16. Detail Node: The right side panel content (Cited By, Reviews, Create Node) should look good on mobile. (#91)
- [x] 17. Detail Node: The user is able to click on the `blue text` in the node content to open the "Cited By" and view the currently highlighted content + all highlights. (#78)

### Author Page (http://knowledgrdemo.mousebelt.com:8080/@oleg)
- [x] 18. Author Page: should look good on desktop and mobile. (#101)
- [x] 19. Author Page: User should be able to sort the author's posts.
- [x] 19. Author Page: User should be able to click on the link to any of the author's posts and see the detail node page.
- [x] 19. Author Page: User should be able to view the comments on any of the author's posts.

**Comment by sos0** [comment]
### Current Limitations
- Mock data currently does not follow the correct logic to fulfill the following:
    - if node A has node B in Citation_1, node B must list node A as Originated_From
    - if node A has some Citation_x, their date must be newer than the original node.
    - The above incorrect logic results in the following wrong UX:
        - The user will see that comments of one node were potentially created _before_ the original node.
        - Node A's comments are not listed as "Cited By:" content in the detail page and vice versa.
- Medium highlight component currently has a bug, so when we highlight text that includes an already existing link, it will not show the correct text in the Create Post panel. It requires some more research to fix this bug.
